# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Domain/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones


    League\Tactician\CommandBus:
        arguments:
            -
                - '@tactician.middleware.command_handler'

    tactician.middleware.command_handler:
        class: League\Tactician\Handler\CommandHandlerMiddleware
        arguments:
            - '@tactician.handler.command_name_extractor.class_name'
            - '@tactician.handler.locator.symfony'
            - '@tactician.handler.method_name_inflector.handle'

    tactician.handler.command_name_extractor.class_name:
        class: League\Tactician\Handler\CommandNameExtractor\ClassNameExtractor

    tactician.handler.locator.symfony:
        class: League\Tactician\Handler\Locator\InMemoryLocator
        calls:
            - method: addHandler
              arguments:
                  - '@App\Application\GetTweet\Query\GetTweetQueryHandler'
                  - 'App\Application\GetTweet\Query\GetTweetQuery'

    tactician.handler.method_name_inflector.handle:
        class: League\Tactician\Handler\MethodNameInflector\HandleInflector

    League\Tactician\Handler\MethodNameInflector\MethodNameInflector: '@tactician.handler.method_name_inflector.handle'

    App\Domain\Tweet\Service\TweetService:
        arguments:
            $tweetRepository: '@App\Infrastructure\TweetRepositoryInMemory'

    App\Infrastructure\Query\QueryBusInterface:
        class: App\Infrastructure\Query\TacticianQueryBus