<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container26m1VPz\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container26m1VPz/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container26m1VPz.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container26m1VPz\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container26m1VPz\App_KernelDevDebugContainer([
    'container.build_hash' => '26m1VPz',
    'container.build_id' => '02525ece',
    'container.build_time' => 1728560597,
], __DIR__.\DIRECTORY_SEPARATOR.'Container26m1VPz');
