<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_infrastructure_tweet_http_tweetconverter_index' => [['userName'], ['_controller' => 'App\\Infrastructure\\Tweet\\Http\\TweetConverterController::index'], [], [['variable', '/', '[^/]++', 'userName', true], ['text', '/tweets']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
